[platformio]
extra_configs = secrets.local.ini

[secrets]
wifi_ssid =
wifi_pass =
script_url =
device_token =

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
    -D WIFI_SSID=\"${secrets.wifi_ssid}\"
    -D WIFI_PASS=\"${secrets.wifi_pass}\"
    -D SCRIPT_URL=\"${secrets.script_url}\"
    -D DEVICE_TOKEN=\"${secrets.device_token}\"
lib_deps =
    bblanchon/ArduinoJson@^7